name: Django Test with PostgreSQL

on:
    workflow_call:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PSQL_USERNAME: luis_dominguez
      PSQL_PASSWORD: Luis#23
      PSQL_DBNAME: luis_dominguezdb
      JWT_TOKEN_TIME: "15"
      PSQL_HOST: localhost
      PSQL_PORT: 5432

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{env.PSQL_USERNAME}}
          POSTGRES_PASSWORD: ${{env.PSQL_PASSWORD}}
          POSTGRES_DB: ${{env.PSQL_DBNAME}}
        #Use 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run tests 
        run: pytest 
      